archives:
  - files:
      - LICENSE
      - README.md
    format: zip
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
#before:
#  hooks:
#    - go mod tidy
builds:
  - binary: '{{ .ProjectName }}'
    main: cmd/main.go
    flags:
      - -trimpath
    goarch:
      - 386
      - amd64
    goos:
      - darwin
      - linux
      - windows
    mod_timestamp: '{{ .CommitTimestamp }}'
changelog:
  skip: true
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
dist: build
env:
  - CGO_ENABLED=0
release:
  draft: true
