name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Generate changelog
        run: |
          mkdir .bin
          curl -L https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_amd64 -o .bin/git-chglog
          chmod +x .bin/git-chglog
          .bin/git-chglog -c .github/changelog/config.yml -o .bin/DRAFT.md $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release -f .github/goreleaser.yml --rm-dist --release-notes=.bin/DRAFT.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
