name: unit tests
on:
  push:
    paths:
      - '**.go'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            .bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Lint source code
        run: make tools lint

      - name: Run unit tests
        run: make test
